### ISSUE TITLE
Enable to store items in an external MinIO instance?

### ISSUE THREAD

**Issue by mzch** [femto-apps/web-file-uploader#30]
If `useSSL` option is configurable, I think Web-File-Uploader can access to an external MinIO instance.
How about?

**Comment by popey456963** [comment]
As a corrollary aspect to this, making it support S3 easily would be really useful I imagine.

**Comment by popey456963** [comment]
You can now do this by providing your parameters to `minio` in the config file now.  You can see the options you can add under "Constructor" here:

https://docs.min.io/docs/javascript-client-api-reference.html

"host" / "endPoint" can be used interchangeably, with "host" overriding the "endPoint" value if set.
