### ISSUE TITLE
Add warnings to files that didn't go through an antivirus run yet

### ISSUE THREAD

**Issue by dimaguy** [femto-apps/web-file-uploader#33]
It is safer for the end user, since files dont immediately go through the scan immediately as one can see on the /info/ of a file

**Comment by popey456963** [comment]
Now we have an interstitial:

![image](https://user-images.githubusercontent.com/1338129/98554396-9085e700-2298-11eb-9199-cd9150541087.png)

It can be overridden by adding the following to a URL:

    overrideVirusCheck=true

e.g.

    http://localhost:3005/uy8b?overrideVirusCheck=true

If the virus checking is disabled on a host, all URLs will be permitted.
