### ISSUE TITLE
Allow downloading all contents on this website as soon as possible.

### ISSUE THREAD

**Issue by hadi99905** [femto-apps/web-file-uploader#50]
I'm not able to download files uploaded on this website make download available as soon as possible.Please

**Comment by dimaguy** [comment]
Files are supposed to be available as soon as they are uploaded. Are you sure the upload completed successfully?

**Comment by hadi99905** [comment]
Yes it is uploaded i will give link of the file
https://femto.pw/umpc
I am not able to download the file can you pls help me

**Comment by dimaguy** [comment]
That link corresponds to a static html file, which is rendered by femto. Youll need to "save link as" or curl/wget it

**Comment by hadi99905** [comment]
Could you please help me download it.It would be a great thing from you.

**Comment by dimaguy** [comment]
I already gave you all instructions you need, I dont know what else to tell you, just right click the link and click save link as

**Comment by hadi99905** [comment]
I am using mobile there is no option "save link as" that file is so
important to me

**Comment by hadi99905** [comment]
Can you provide a link to directly download that file.

**Comment by popey456963** [comment]
I'm closing this as it's not a bug with `web-file-uploader`.

**Comment by hadi99905** [comment]
Can you give me the link please

**Comment by hadi99905** [comment]
Can you please give me his email address? Just once.Please sir i request🙏

**Comment by dimaguy** [comment]
You ALREADY have both the link and instructions to get the html file

**Comment by hadi99905** [comment]
I want the pdf not the html file

**Comment by dimaguy** [comment]
There is no pdf in that file. I am sorry but on that link there is only an html static page

**Comment by hadi99905** [comment]
He uploaded 2.00gb file i am looking forward to download that.

**Comment by dimaguy** [comment]
He uploaded the wrong thing. I am sorry

**Comment by hadi99905** [comment]
You are saying that coz you don't know what to do lol😂

**Comment by dimaguy** [comment]
I know fairly well what to do: tell you to ring your friend so he uploads the right thing.

HE DID NOT UPLOAD THE PDF FILE AS YOU CAN SEE ON THIS LINK

https://femto.pw/info/umpc

**Comment by hadi99905** [comment]
Please help me could you please give me his email address please

**Comment by dimaguy** [comment]
That is against GDPR, so not even the owner can provide such thing.

**Comment by hadi99905** [comment]
So what should I do? I want that file how can i contact him i saw only one
file on internet.

**Comment by dimaguy** [comment]
You are out of luck
